version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda-items
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - network
  agenda-item-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agenda-item-app
    environment:
      ENV_CONTEXT_PATH: /sicred
      ENV_DATASOURCE.PASSWORD: root
      ENV_DATASOURCE.URL: jdbc:mysql://mysql:3306/agenda-items
      ENV_DATASOURCE.USER: root
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - network

volumes:
  mysql-data:

networks:
  network:
