server:
  port: ${ENV_SERVER.PORT:8080}
  servlet:
    context-path: ${ENV_CONTEXT_PATH}

spring:
  application:
    name: agenda
  datasource:
    url: ${ENV_DATASOURCE.URL}?createDatabaseIfNotExist=true
    username: ${ENV_DATASOURCE.USER}
    password: ${ENV_DATASOURCE.PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
  file:
    name: app.log